### PR TITLE
chore: remove cert error message, update docs links

### PR DESCRIPTION
**Pull request by dkwon17**
Signed-off-by: David Kwon <dakwon@redhat.com>

### What does this PR do?
* Updates the documentation links since the current one's point to outdated urls
* Removes the cert error from code base

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-3024

### Is it tested? How?

To verify that the following docs links are updated, here are the screenshots for where to access them:

<details>
<summary>new documentation link in `BRANDING_DEFAULT.links`</summary>

image

</details>

<details>
<summary>BRANDING_DEFAULT.docs.devfile</summary>

image

</details>

<details>
<summary>BRANDING_DEFAULT.docs.workspace</summary>

image

</details>

<details>
<summary>BRANDING_DEFAULT.docs.storageTypes</summary>

image

</details>

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]
:+1:

**Comment by olexii4** [comment]
@dkwon17  Could you fix the build?

**Review by olexii4 — APPROVED** [review]
LGTM

@dkwon17  Fix the build please:
```yarn format:fix``` 
```yarn lint:fix```

**Comment by dkwon17** [comment]
@olexii4 thank you for the reminder, I updated the PR

**Pull request merged**
