### PR TITLE
Fix an ability to update existing DevWorkspaceTemplates

### PR DESCRIPTION
**Pull request by olexii4**
### What does this PR do?
Fix an ability to update existing DevWorkspaceTemplates

### What issues does this PR fix or reference?
fixes https://github.com/eclipse/che/issues/22291

### Is it tested? How?

1. Deploy Eclipse-CHE with an image from the current PR.
2. Open the 'Create Workspace' page. Create a new workspace with URL```{CHE-Server}#https://github.com/eclipse-che/che-dashboard.git```.
3. Open Swagger ```{CHE-Server}/dashboard/api/swagger```. Found the created DevworkspaceTemplate:
```
    "kind": "DevWorkspaceTemplate",
    "metadata": {
      "annotations": {
        "che.eclipse.org/components-update-policy": "managed",
        "che.eclipse.org/plugin-registry-url": ...
      },
      ...
```

Putch  the template with 
```
[
  {
    "op": "replace",
    "path": "/spec/commands",
    "value": []
  }
]
```
4. Check that the new value for commands ``` "value": []``` was applied.
5. Go back to Dashboard and refresh the page.
6. Open Swagger again and check that the target template was updated and ```/spec/commands``` has a value different from an empty array.

### CODE REVIEW

**Comment by olexii4** [comment]
Знімок екрана 2023-06-27 о 18 41 51
Знімок екрана 2023-06-27 о 18 43 27
Знімок екрана 2023-06-27 о 18 56 17

**Review by ibuziuk — APPROVED** [review]
:+1: @dmytro-ndp could you please review

**Review by dmytro-ndp — APPROVED** [review]
Test scenario from PR has passed in Eclipse Che Next with quay.io/eclipse/che-dashboard:pr-844, with one difference in step 4: there was `"commands": []` in DevWorkspace Template:
Screenshot from 2023-07-07 19-58-20
With that in mind PR looks good to merge.

@olexii4 : It would also be great to have an explanation about how exactly this PR is addressing the questions raised by [the issue being fixed](https://github.com/eclipse/che/issues/22291):
1) Are the existing DevWorkspaecTemplates updated when users restarts an existing workspace?
2) Is a new image pulled when a user restarts an existing workspace?

**Comment by olexii4** [comment]
@dmytro-ndp 
1. Existing DevWorkspaecTemplates are updated when users open (start) an existing workspace because when you click on the workspace and when the user clicks on the "restart workspace" button from IDE, it will redirect to the start workspace page(the same effect if you refresh the che-dashboard page).

For testing this scenario:
 - Create a new workspace and open IDE.
 - Open a new tab with che-dashboard and stop the target workspace.
Знімок екрана 2023-07-10 о 14 48 45
 - Patch the created template with a swagger.
 - Open the tab with IDE and press the "Restart your workspace" button. It will redirect to the start workspace page.
Знімок екрана 2023-07-10 о 14 44 07
 - After restarting check created template with a swagger. The patch should be applied.
 
2. A new image could be pulled when users restart an existing workspace. It depends on the ```imagePullPolicy``` (Always, IfNotPresent, Never):
https://github.com/devfile/devworkspace-operator/blob/main/apis/controller/v1alpha1/devworkspaceoperatorconfig_types.go#L73.

**Pull request merged**
