### PR TITLE
Fix conversion issue

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

This PR adds a sidecar policy `mergeImage` to converted devfiles v2 to run plug-ins in sidecar containers (it's important if there isn't any dev container).

### What issues does this PR fix or reference?

fixes https://github.com/eclipse/che/issues/21120

### Is it tested? How?

1. Create Che7 workspaces using swagger (`https://che-host/swagger`) from these devfiles: [apache-camel-k](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/apache-camel-k/devfile.yaml), [che4z](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/che4z/devfile.yaml), [rust](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/rust/devfile.yaml)
2. Convert each workspace and make sure there aren't any errors.

### CODE REVIEW

**Review by olexii4 — APPROVED** [review]

**Review by olexii4 — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]
:+1: verified against dogfooding
once backported to 7.46.x we can close https://github.com/eclipse/che/issues/21120 \o/

**Comment by benoitf** [comment]
IMHO it should only do that if there is no user component.

**Comment by akurinnoy** [comment]
Hi @benoitf,

How do I correctly detect if there is a user component?

**Pull request merged**
