### PR TITLE
Remove an old authorization flow with Keycloak

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Remove an old authorization flow with Keycloak.

### What issues does this PR fix or reference?
fixes https://issues.redhat.com/browse/CRW-2875

### Is it tested? How?

It could be tested by deploying Eclipse Che on  OpenShift.

1. Deploy Che.
```
chectl server:deploy \
    --installer=operator \
    --platform=openshift \
    --che-operator-cr-patch-yaml=./custom.yaml
```
File **custom.yaml**
```
spec:
  server:
    dashboardImage: quay.io/eclipse/che-dashboard:pr-524
```
2. Configure 5 minutes timeout in OCP cluster settings
```
oc patch OAuth/cluster -p '{ "spec": { "tokenConfig": { "accessTokenInactivityTimeout": "5m" }}}' --type merge
```
3. Go to the Dashboard page and login into as an OpenShift user.

4. Wait 5 minutes on OpenShift login session to be expired.

5. Go to the Dashboard page again and refresh it.
6. Dashboard should redirect to OCP OAuth page.

### CODE REVIEW

**Review by ibuziuk — COMMENTED** [review]
@olexii4 thanks for the fix, however I was not able to verify against dogfooding :shrug: 
```
ERROR in ./src/index.ts
Module not found: Error: Can't resolve './api/kubeConfigAPI' in '/home/ibuziuk/git/che-dashboard/packages/dashboard-backend/src'
 @ ./src/index.ts 33:24-54
```

**Comment by olexii4** [comment]
> @olexii4 thanks for the fix, however, I was not able to verify against dogfooding 🤷
> 
> ```
> ERROR in ./src/index.ts
> Module not found: Error: Can't resolve './api/kubeConfigAPI' in '/home/ibuziuk/git/che-dashboard/packages/dashboard-backend/src'
>  @ ./src/index.ts 33:24-54
> ```

@ibuziuk I have created a fixup

**Review by ibuziuk — COMMENTED** [review]
@olexii4 thanks, but still does not work for me against dogfooding - the UD has been started but the loader is shown forever when accessing 8000:

````
Static server's serving "/home/ibuziuk/git/che-dashboard/packages/dashboard-frontend/lib/public" on 0.0.0.0:8080/
Che Dashboard swagger is running on "dashboard/api/swagger".
├── * (OPTIONS)
└── / (-)
    ├── * (HEAD, GET)
    ├── api (-)
    │   ├── / (DELETE, GET, HEAD, PATCH, POST, PUT, OPTIONS)
    │   │   └── / (DELETE, GET, HEAD, PATCH, POST, PUT, OPTIONS)
    │   ├── /* (DELETE, GET, HEAD, PATCH, POST, PUT, OPTIONS)
    │   └── /websocket (GET)
    ├── dashboard (-)
    │   ├── /api (-)
    │   │   ├── /cluster-config (GET)
    │   │   ├── /cluster-info (GET)
    │   │   ├── /namespace/:namespace (-)
    │   │   │   ├── /devworkspaceId/:devworkspaceId/kubeconfig (POST)
    │   │   │   ├── /devworkspaces (POST, GET)
    │   │   │   │   └── /:workspaceName (PATCH, GET, DELETE)
    │   │   │   ├── /devworkspacetemplates (POST, GET)
    │   │   │   │   └── /:templateName (PATCH)
    │   │   │   └── /dockerconfig (PUT, GET)
    │   │   ├── /server-config/default-plugins (GET)
    │   │   ├── /swagger (GET)
    │   │   │   ├── / (GET)
    │   │   │   ├── /* (GET)
    │   │   │   ├── /initOAuth (GET)
    │   │   │   ├── /json (GET)
    │   │   │   ├── /static/* (HEAD, GET)
    │   │   │   ├── /uiConfig (GET)
    │   │   │   └── /yaml (GET)
    │   │   └── /websocket (GET)
    │   └── /f (GET)
    └── f (GET)

(node:14866) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Server listening at http://localhost:8080/
```

There are no errors in the logs :shrug:

![image](https://user-images.githubusercontent.com/1461122/168311814-ebb02b2a-faeb-461b-aa52-ffd6985f9d47.png)

**Comment by olexii4** [comment]
> @olexii4 thanks, but still does not work for me against dogfooding - the UD has been started but the loader is shown forever when accessing 8000:
> 
> ```
> Static server's serving "/home/ibuziuk/git/che-dashboard/packages/dashboard-frontend/lib/public" on 0.0.0.0:8080/
> Che Dashboard swagger is running on "dashboard/api/swagger".
> ├── * (OPTIONS)
> └── / (-)
>     ├── * (HEAD, GET)
>     ├── api (-)
>     │   ├── / (DELETE, GET, HEAD, PATCH, POST, PUT, OPTIONS)
>     │   │   └── / (DELETE, GET, HEAD, PATCH, POST, PUT, OPTIONS)
>     │   ├── /* (DELETE, GET, HEAD, PATCH, POST, PUT, OPTIONS)
>     │   └── /websocket (GET)
>     ├── dashboard (-)
>     │   ├── /api (-)
>     │   │   ├── /cluster-config (GET)
>     │   │   ├── /cluster-info (GET)
>     │   │   ├── /namespace/:namespace (-)
>     │   │   │   ├── /devworkspaceId/:devworkspaceId/kubeconfig (POST)
>     │   │   │   ├── /devworkspaces (POST, GET)
>     │   │   │   │   └── /:workspaceName (PATCH, GET, DELETE)
>     │   │   │   ├── /devworkspacetemplates (POST, GET)
>     │   │   │   │   └── /:templateName (PATCH)
>     │   │   │   └── /dockerconfig (PUT, GET)
>     │   │   ├── /server-config/default-plugins (GET)
>     │   │   ├── /swagger (GET)
>     │   │   │   ├── / (GET)
>     │   │   │   ├── /* (GET)
>     │   │   │   ├── /initOAuth (GET)
>     │   │   │   ├── /json (GET)
>     │   │   │   ├── /static/* (HEAD, GET)
>     │   │   │   ├── /uiConfig (GET)
>     │   │   │   └── /yaml (GET)
>     │   │   └── /websocket (GET)
>     │   └── /f (GET)
>     └── f (GET)
> 
> (node:14866) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> Server listening at http://localhost:8080/
> ```
> 
> There are no errors in the logs :shrug:
> 
> image
>  
> ```

@ibuziuk Please, try the latest version. I successfully tested it with the latest changes(OpenShift).
I tested with docker.io/olexii4dockerid/che-dashboard:keycloakNew

**Comment by ibuziuk** [comment]
also on logout locally I got the following error:

```{"message":"Route GET:/oauth/sign_out not found","error":"Not Found","statusCode":404}```

**Review by ibuziuk — APPROVED** [review]

**Comment by ibuziuk** [comment]
@olexii4 once merged could you please cherry-pick to 7.46.x

**Review by akurinnoy — APPROVED** [review]
LGTM

**Pull request merged**
