### PR TITLE
chore: bump to newer base images using node...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore: bump to newer base images using node 16.20.1 (and alpine 3.15 -> 3.18); fix hadolint warnings for dockerfile and bash commands

Change-Id: I232ebb476c2d5ff29e102ec06fe7365d181ed331
Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-4820

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
Tests done:

```
podman build . -f build/dockerfiles/rhel.Dockerfile -t quay.io/eclipse/che-dashboard:node18rhel8
Successfully tagged quay.io/eclipse/che-dashboard:node18rhel8
```

```
yarn;yarn build; podman podman build . -f build/dockerfiles/skaffold.Dockerfile -t quay.io/eclipse/che-dashboard:node18skaf
Successfully tagged quay.io/eclipse/che-dashboard:node18skaf
```

```
podman build . -f build/dockerfiles/Dockerfile -t quay.io/eclipse/che-dashboard:node18alpine318
...
```

**Review by akurinnoy — APPROVED** [review]

**Review by akurinnoy — APPROVED** [review]

**Review by olexii4 — APPROVED** [review]

**Comment by SDawley** [comment]
retest

**Comment by SDawley** [comment]
the errors looked like network issues

**Pull request merged**
