### PR TITLE
Prevent starting a Git+SSH factory if no SSH keys configured

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

This PR prevents creating new workspaces via Git+SSH factory URL (on the Create Workspace page) until SSH keys are configured by the user.

<details>
<summary>Screencast</summary>

https://github.com/eclipse-che/che-dashboard/assets/16220722/d85e1348-c980-4b82-a755-1da73f301792

</details>

### What issues does this PR fix or reference?

resolves https://github.com/eclipse/che/issues/22728

### Is it tested? How?

**TODO**

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]

**Review by olexii4 — APPROVED** [review]
LGTM

**Comment by olexii4** [comment]
@akurinnoy I found a regression with these changes:
I cannot create a new workspace with the **Import from Git** widget in the case with additional parameters.

Step to reproduce:
1. Open **Create Workspace** page.
2. Paste ```https://github.com/eclipse-che/che-dashboard&editor-image=quay.io/mloriedo/che-code:copilot-builtin``` .
 
Знімок екрана 2024-01-19 о 15 37 08

3. Press **Create&Open** button. 

4. The next warning will appear:

Знімок екрана 2024-01-19 о 15 36 25

PS
It happens because of additional encoding of the **Import from Git** input.

**Comment by akurinnoy** [comment]
@olexii4 Thanks for the feedback, I've rebased my branch. I hope this will resolve the regression you found.

**Review by olexii4 — APPROVED** [review]
@akurinnoy  I retested changes from this PR and the regression was fixed.

**Comment by ibuziuk** [comment]
@musienko-maxim @dmytro-ndp folks, could you please take a look on why PR checks are failing?

**Pull request merged**
