### PR TITLE
chore: bump to the latest theia DW library

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Use the newer theia library

### What issues does this PR fix or reference?
https://github.com/eclipse-che/che-theia/pull/1249
Fixes https://github.com/eclipse/che/issues/20725

### Is it tested? How?
It was tested using the repositories listed in the issue (using the factory workflow)

### CODE REVIEW

**Review by olexii4 — APPROVED** [review]

**Comment by olexii4** [comment]
I checked it. It is working as expected.
@benoitf Could you run 'yarn install' in the root directory? It will bring some changes to 'yarn.lock' file and these changes should be added too.

**Comment by benoitf** [comment]
@olexii4 I think I already ran 'yarn install' and there are yarn.lock changes as part of this PR https://github.com/eclipse-che/che-dashboard/pull/395/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de

**Comment by olexii4** [comment]
@benoitf  When I build UD from your PR I saw changes in 'yarn.lock'. I checked it twice.
Ok. Let it be. I will fix it after.

**Comment by benoitf** [comment]
@olexii4 I've committed updated yarn.lock

**Review by akurinnoy — APPROVED** [review]

**Pull request merged**
