### PR TITLE
feat: implement an ability to start workspaces in Safe Mode

### PR DESCRIPTION
**Pull request by olexii4**
### What does this PR do?
 Implement an ability to start workspaces in Safe Mode.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/22228, https://github.com/eclipse/che/issues/22391 and https://github.com/eclipse/che/issues/22274

### Is it tested? How?

1. Deploy Eclipse-CHE with an image from the current PR.
2. Open the 'Create Workspace' page. Create a new workspace with ```URL{CHE-Server}#https://github.com/olexii4/che-dashboard.git```.
3. Waite for an error message:
Знімок екрана 2023-08-14 о 21 46 12
4. Click the "Restart in Safe mode" button.
5.  Wait for the target workspace to restart and open IDE.
Знімок екрана 2023-08-14 о 21 48 32
Знімок екрана 2023-08-14 о 22 03 57

### CODE REVIEW

**Review by akurinnoy — APPROVED** [review]

**Review by akurinnoy — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
@olexii4: PR review results:
1. IMHO it would be helpful to add the message / label to start workspace page that workspace is starting in safe mode with limited functionality.

2. So that PR description said that it fixes https://github.com/eclipse/che/issues/22391, I made sure that there are no "Open in Verbose mode" items in left panel and workspaces page in Dashboard

3. I have successfully executed steps from section "**Is it tested? How?**".
Notes:
3.1 Extensions view was broken and failed to obtain list of extensions: "Error while fetching extensions. Server returned 500":
Screenshot from 2023-08-17 13-12-37
There was no such a problem when create regular workspace from Dashboard.

3.2 https://github.com/eclipse/che/issues/22228 contains requirements to workspace which is run in safe mode:
- `ephemeral storage`
  currently workspace started using per-user storage:
screenshot-eclipse-che apps ocp413-dnochev crw-qe com-2023 08 17-13_25_40
- `no route/ingress is created (the editor endpoints with urlRewriteSupport: false are ignored)`
 there were 3 routes created when start workspace in safe mode:
Screenshot from 2023-08-17 13-40-35

**Comment by olexii4** [comment]
@dmytro-ndp 

> 3\. I have successfully executed steps from section "**Is it tested? How?**".
>     Notes:
>     3.1 Extensions view was broken and failed to obtain list of extensions: "Error while fetching extensions. Server returned 500":

It is not an issue with this PR. We have the same problems with [dogfooding](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/dashboard/):

Знімок екрана 2023-08-17 о 15 30 46

**Comment by dmytro-ndp** [comment]
@olexii4 : thanks for the comments.
I have opened a ticket about popular extensions problem: https://github.com/eclipse/che/issues/22439

**Comment by olexii4** [comment]
@l0rd I have some problems with removing ```route/ingress``` which was created (the editor endpoints with ```urlRewriteSupport: false``` are ignored). Could you elaborate in detail?

**Comment by ibuziuk** [comment]
> I have some problems with removing route/ingress which was created (the editor endpoints with urlRewriteSupport: false are ignored). Could you elaborate in detail?

I believe this is not needed, the issue boils down to the following user story "As a user when workspace fails to start I should always have the option to start with the default devfile". Currently, this possibility is missing on the UI - https://github.com/eclipse/che/issues/22228#issuecomment-1634100518

**Review by ibuziuk — APPROVED** [review]

**Comment by l0rd** [comment]
I haven't tested the PR but I am ok if we drop the no routes requirement. It's not clear from the PR description if the other requirements are satisfied:
- `.vscode/editor.yaml` is not resolved (use default component, default editor)
- ephemeral storage
- any operation that uses the git service REST API is avoided

Also we should rephrase "Restart in Safe mode" to "Restart with default Devfile". 

And I don't understand what the link "Open in debug mode" does.

**Comment by l0rd** [comment]
Ok thanks for the explanation. So "Open in debug mode" only adds `controller.devfile.io/debug-start=true` or also restarts the workspace? As a user I would expect to see more details when I click "Open in debug mode" and I would be disappointed otherwise. Also I think that we should allow adding `controller.devfile.io/debug-start=true` even if the workspace is restarted with the Default Devfile (i.e. it should be a separated toggle) but with current status those look like 3 different alternatives.

**Comment by olexii4** [comment]
> * any operation that uses the git service REST API is avoided

@l0rd  It is not completely clear to me. Could you explain more about what it could be?

We added `projects` from the origin devfile into the default devfile. 
For example:
```
projects:
  - attributes:
      source-origin: branch
    git:
      checkoutFrom:
        revision: CRW-3440
      remotes:
        origin: https://github.com/olexii4/devfile-converter.git
    name: devfile-converter
```
Should we remove it at all?

**Comment by olexii4** [comment]
> Ok thanks for the explanation. So "Open in debug mode" only adds `controller.devfile.io/debug-start=true` or also restarts the workspace? As a user I would expect to see more details when I click "Open in debug mode" and I would be disappointed otherwise. Also I think that we should allow adding `controller.devfile.io/debug-start=true` even if the workspace is restarted with the Default Devfile (i.e. it should be a separated toggle) but with current status those look like 3 different alternatives.

1. "Open in debug mode" will start the workspace with `controller.devfile.io/debug-start=true`.

2. With the current status we have 3 different alternatives: 
 a. 'Restart' - just restart the workspace.
 b. 'Restart in Safe mode' - patches the targes devWorkspace and devWorkspaceTemplate. It is an unrevertable procedure from CHE dashboard.
 c.  'Open in Debug mode' - Start the workspace with `controller.devfile.io/debug-start=true`
 
 @l0rd  WDYT?

**Comment by ibuziuk** [comment]
@l0rd Since this PR blocks others, wdyt about merging it in the current state, and we can discuss further improvements as part of https://github.com/eclipse/che/issues/22228 and update the issue accordingly?

**Comment by l0rd** [comment]
> @l0rd Since this PR blocks others, wdyt about merging it in the current state, and we can discuss further improvements as part of [eclipse/che#22228](https://github.com/eclipse/che/issues/22228) and update the issue accordingly?

I am ok with merging this right away and fixing the rest later. But the critical part to address is not about [eclipse/che#22228](https://github.com/eclipse/che/issues/22228) but about the new "Open in Debug mode" link that's adding confusion more then anything else.

**Comment by olexii4** [comment]
> > ```
> > 1. "Open in debug mode" will start the workspace with `controller.devfile.io/debug-start=true`.
> > 
> > 2. With the current status we have 3 different alternatives:
> >    a. 'Restart' - just start the workspace again.
> >    b. 'Restart in Safe mode' - patches the targes devWorkspace and devWorkspaceTemplate(default devfile and default editor applies). It is an unrevertable procedure from CHE dashboard.
> >    c.  'Open in Debug mode' - Start the workspace with `controller.devfile.io/debug-start=true`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @l0rd WDYT?
> 
> It's disappointing because I am expecting to view more information when the workspace is restarted but I won't.
> 
> It's confusing because how do I know if Debug mode means using the default devfile or the user provided one?



> It's disappointing because I am expecting to view more information when the workspace is restarted but I won't.
> 
> It's confusing because how do I know if Debug mode means using the default devfile or the user provided one?

The current implementation includes the following messages: 
1.  Starting workspace .....
2. Starting workspace ..... in Safe mode
3. Starting  workspace ..... in Debug mode
Знімок екрана 2023-08-21 о 16 15 37
It was feedback from @dmytro-ndp.

**Comment by olexii4** [comment]
I have added several fixes:

1. Renamed 'Restart in Safe mode' -> 'Restart with default Devfile'
2. Removed 'Open in Debug mode' from the factory flow.

Знімок екрана 2023-08-29 о 20 31 36

Знімок екрана 2023-08-29 о 23 52 00

**Pull request merged**
