### PR TITLE
Check for git remotes

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1217

### CODE REVIEW

**Review by olexii4 — APPROVED** [review]
LGTM

**Review by olexii4 — APPROVED** [review]
LGTM

**Review by ibuziuk — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
Actually, I need help from to see Dev Spaces samples and so be able to create JBoss EAP 8.0 workspace when test cherry-pick in 7.92 https://github.com/eclipse-che/che-dashboard/pull/1218 using Dev Spaces 3.17.0 + [quay.io/eclipse/che-dashboard:pr-1218](http://quay.io/eclipse/che-dashboard:pr-1218).
Screenshot from 2024-10-10 20-07-19

Also I haven't reproduced the issue on the Dev Spaces 3.17.0.RC-devspaces-operator-bundle-container-3.17-32 WITHOUT [quay.io/eclipse/che-dashboard:pr-1218](http://quay.io/eclipse/che-dashboard:pr-1218) using factory URL https://github.com/jbossas/eap-devfile-examples/blob/eap-8.0.x/devfile.yaml you mentioned in PR into the main https://github.com/eclipse-che/che-dashboard/pull/1217
Screenshot from 2024-10-10 20-30-02

**Review by dmytro-ndp — APPROVED** [review]
@tolusha prepared Eclipse Che Dashboard image built from this PR with Dev Spaces 3.17 samples.
I have tested it with Dev Spaces 3.17.0.RC, and didn't encounter warning popup when started "JBoss EAP 8.0" workspace:
[scrnli_Sy8YCpFPNS1802.webm](https://github.com/user-attachments/assets/36c6fe85-2d94-49e3-83e1-1ca20b84de14)

Good job, @akurinnoy !

**Pull request merged**
