### PR TITLE
Add isForbidden status check

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Add handler for 403 server error.

### What issues does this PR fix or reference?
fixes https://issues.redhat.com/browse/CRW-2690

### CODE REVIEW

**Review by ibuziuk — COMMENTED** [review]
@olexii4 tried to verify but got:

```
[INFO] Compiling frontend package
$ webpack --progress --color --config webpack.config.dev.js
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve has an unknown property 'fallback'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, ignoreRootsErrors?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, preferAbsolute?, resolver?, roots?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
   -> Options for the resolver
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

**Comment by olexii4** [comment]
> @olexii4 tried to verify but got:
> 
> ```
> [INFO] Compiling frontend package
> $ webpack --progress --color --config webpack.config.dev.js
> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
>  - configuration.resolve has an unknown property 'fallback'. These properties are valid:
>    object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, ignoreRootsErrors?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, preferAbsolute?, resolver?, roots?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
>    -> Options for the resolver
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command failed with exit code 1.
> ```

Sorry. It was linter. I added a fix.

**Comment by nickboldt** [comment]
Everything but happy path is now passing. Does that mean we can merge and backport to 7.46.x?

Need this merged & built ASAP so we can verify and release on Monday...

**Review by ibuziuk — APPROVED** [review]
tested locally against dogfooding :+1:

**Review by akurinnoy — APPROVED** [review]

**Pull request merged**
