### PR TITLE
Add ability to show a warning banner by configuring CheCluster CR (#466)

### PR DESCRIPTION
**Pull request by ibuziuk**
Backporting  https://github.com/eclipse/che/issues/20724 to 7.42.x

PR contains a number of commits to make the warning header functionality work as expected. Verified against the `che-dev` dogfooding instance:

image

### CODE REVIEW

**Review by akurinnoy — APPROVED** [review]

**Review by olexii4 — APPROVED** [review]

**Comment by ibuziuk** [comment]
@olexii4 thanks for the review, just wondering about the removal of the `packages/dashboard-backend/src/services/kubeclient/keycloak.ts` will it affect the che-server-based setup / CRW 2.15.3? I verified only against che-dev cluster with DevWorkspace engine enabled by default and spinning the cluster bot with CRW 2.15.2 atm to make sure that it will work as expected.

**Comment by nickboldt** [comment]
Yikes, that's a lot of changes. Some seem unrelated... like removing stuff about keycloak?

**Comment by nickboldt** [comment]
Where is the displayed message & link configured? I scrolled the whole PR but got lost in a typescript haze, didn't see any mention of a blog post or whatnot.

**Comment by ibuziuk** [comment]
the message will be configured on the codeready-worskapces-operator defaults for `spec.dashboard.warning`

**Comment by nickboldt** [comment]
hmm. would be a tad easier to handle if it was in the CSV vs. in the operator itself, but *shrug*

**Comment by nickboldt** [comment]
anyway we can add / change annotations in https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/codeready-workspaces-operator/build/scripts/sync-che-operator-to-crw-operator.sh#L249-L258 when transforming upstream Che Operator into Dev Spaces Operator

**Comment by ibuziuk** [comment]
@nickboldt the PR for the operator has been merged - https://github.com/eclipse-che/che-operator/pull/1339
from the downstream operator perspective please provide the default value for `spec.dashboard.warning` it could be `lorem ipsum` for now

**Comment by olexii4** [comment]
@ibuziuk I have returned `packages/dashboard-backend/src/services/kubeclient/keycloak.ts` back:
[commit](https://github.com/eclipse-che/che-dashboard/pull/478/commits/6a62ebc784f8b5b93e62c07ad535c7157d1a8751).

**Pull request merged**
