### PR TITLE
Fix revoking of Git service tokens

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

This PR fixes two bugs related to revoking tokens on the Git Services page:
- the Revoke button becomes disabled after revoking the selected git service token (https://github.com/eclipse/che/issues/22827);
  <details>
  <summary>demo 1</summary>

  https://github.com/eclipse-che/che-dashboard/assets/16220722/3f9d9527-7fb3-40bf-b975-02be1438daba

  </details>
- switching between tabs doesn't prevent revoking the git service token (https://github.com/eclipse/che/issues/22790).
  <details>
  <summary>demo 2</summary>

  https://github.com/eclipse-che/che-dashboard/assets/16220722/1cd5adbe-30ba-45d3-837d-edc3dfa2898b

  </details>

### What issues does this PR fix or reference?

fix https://github.com/eclipse/che/issues/22827
fix https://github.com/eclipse/che/issues/22790

### Is it tested? How?

See the screencasts above.

### CODE REVIEW

**Review by olexii4 — APPROVED** [review]
LGTM
Знімок екрана 2024-03-11 о 16 29 49

**Comment by artaleks9** [comment]
@akurinnoy @vinokurig 
on bitucket-server-oauth2, I faced out with the git service `Authorization` is still active after revoke application

**Screenshot:**
che-bb-server-oauth2-authorization

Video:
https://www.awesomescreenshot.com/s/folder/F0X95mwQ39/61db27e9cbe6db3b59ba4e77a2de84dc

-----
I'll verify gitlab-server to have all checks

**Comment by artaleks9** [comment]
The functionality of gitlab-server **works as expected**

**Comment by vinokurig** [comment]
@artaleks9 
> on bitucket-server-oauth2, I faced out with the git service Authorization is still active after revoke application

Reopened the related issue: https://github.com/eclipse/che/issues/22836

**Pull request merged**
