### PR TITLE
Handle new factory link while unauthorized 

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Fix accept factory flow with native authentication

### What issues does this PR fix or reference?
fixes https://github.com/eclipse/che/issues/20463

### Is it tested? How?

These changes depend on https://github.com/eclipse-che/che-operator/pull/1360

1. Deploy Che with DevWorkspace enabled and native authentication.
Example:
```bash
chectl server:deploy \
    --installer=operator \
    --platform=minikube \
    --che-operator-cr-patch-yaml=./custom-che-server.yaml \
    --che-operator-image=docker.io/olexii4dockerid/che-operator:next
```
File **custom-che-server.yaml**
```
spec:
 server:
   dashboardImage: quay.io/eclipse/che-dashboard:pr-501
```
2. Try to accept factory with URL without being logged in, like 
```$CHE_HOST#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2```.
3. Check that Dashboard is opened with factory flow
```$CHE_HOST/dashboard/#/load-factory?url=https://github.com/che-samples/java-spring-petclinic/tree/devfilev2```.

### CODE REVIEW

**Comment by ibuziuk** [comment]
@olexii4 is it still draft or ready for review?

**Comment by olexii4** [comment]
> @olexii4 is it still draft or ready for review?

@ibuziuk  It is still draft.  It depends on some changes in [che-operator](https://github.com/eclipse-che/che-operator) because we need to add [skipAuthPaths](https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/gateway/oauth_proxy.go#L121).
Discuss changes with @tolusha. Working on PR for che-operator(fix tests).

**Review by akurinnoy — APPROVED** [review]
Great job, Oleksii!

**Review by ibuziuk — APPROVED** [review]
Indeed, great job :+1: 
verified on RHPDS with `#` and `f?url`
please cherry-pick to 7.46.x once merged

**Comment by l0rd** [comment]
@olexii4 I am not able to start workspaces with a `<che-host>/#<github-repo-url>` link on the dogfooding instance today. I suspect that this has something to do with this PR:

- [`<che-host>/#<github-repo-url>`](
https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/eclipse-che/che-docs) **<== KO**

- [`<che-host>/dashboard/#/load-factory?url=<github-repo-url>`](
https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/dashboard/#/load-factory?url=https://github.com/eclipse-che/che-docs) **<== OK**


dogfooding-url-failing

**Comment by olexii4** [comment]
> * [`<che-host>/#<github-repo-url>`](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/eclipse-che/che-docs)

@l0rd I have checked <che-host>/#<github-repo-url>  with https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/eclipse-che/che-dashboard. Everything works on my side.

**Comment by l0rd** [comment]
@olexii4 it works on my side too today 🤷‍♂️

**Pull request merged**
