### PR TITLE
Upgrade `react-router-dom`

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

This PR upgrades the `react-router-dom` to v6.

### What issues does this PR fix or reference?

resolve https://github.com/eclipse-che/che/issues/23136

### Is it tested? How?

Unit tests

### CODE REVIEW

**Comment by ibuziuk** [comment]
@akurinnoy looks like quite a few PR checks are failing atm

**Comment by akurinnoy** [comment]
@ibuziuk should be fixed now

**Review by olexii4 — APPROVED** [review]
LGTM

**Comment by olexii4** [comment]
These changes includes a fix for https://issues.redhat.com/browse/CRW-7211

**Pull request merged**
