### PR TITLE
Fix the bug when kubeconfig file content is collapsed to one line after workspace restart

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
1. Change the parse format from JSON to YAML as the default format of the `oc` and `kubectl` tools is YAML.
2. Do not substring new line when fetching the kubeconfig file content.

### What issues does this PR fix or reference?
fixes https://github.com/eclipse-che/che/issues/23238

### Is it tested? How?

1. Deploy Che with the dashboard pull request image: `quay.io/eclipse/che-dashboard:pr-1279`
2. Apply [Persistent user home](https://eclipse.dev/che/docs/stable/administration-guide/about-persistent-user-home/).
3. Start a workspace, open the `/home/user/.kube/config` file, see that the content is YAML.
4. Open a new terminal and oc login to a kubernetes cluster.
5. Restart the workspace, execute `oc whoami` from the terminal.

See: the oc command works, the kubeconfig file is valid.

### CODE REVIEW

**Comment by olexii4** [comment]
@vinokurig Could you add the proper test for your changes?

**Review by ibuziuk — COMMENTED** [review]
@vinokurig would it be possible to add test(s) for that ?

**Comment by vinokurig** [comment]
@ibuziuk @olexii4 Added test.

**Comment by olexii4** [comment]
@vinokurig Could you fix the **build-and-test** checks, please?

**Review by akurinnoy — APPROVED** [review]

**Comment by artaleks9** [comment]
Verified on Eclipse Che with `quay.io/eclipse/che-dashboard:pr-1279` - **the functionality works properly**

**Review by artaleks9 — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [dashboard_3.x/607](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.x/607/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.x/607/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.x/607/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.x/607/git)

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [sync-to-downstream_3.x/8346](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8346/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8346/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8346/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8346/git)

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [get-sources-rhpkg-container-build_3.x/8442](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8442/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8442/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8442/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8442/git)

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [get-sources-rhpkg-container-build_3.x/8442](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8442/): [FAILURE](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8442/)<br /><blockquote>dashboard : 3.x :: <a href=''> Failed in  </a> : BREW:BUILD/STATUS:UNKNOWN <br /> FAILURE:; copied to quay</blockquote>

**Pull request merged**
