### PR TITLE
Upgrade @eclipse-che/che-devworkspace-generator and @devfile/api

### PR DESCRIPTION
**Pull request by olexii4**
### What does this PR do?
Upgrade @eclipse-che/che-devworkspace-generator and @devfile/api.

### What issues does this PR fix or reference?
fixes https://github.com/eclipse-che/che/issues/23288, https://github.com/eclipse-che/che/issues/23201

### CODE REVIEW

**Review by svor — APPROVED** [review]
should fix this issue as well
https://github.com/eclipse-che/che/issues/23201

**Review by akurinnoy — APPROVED** [review]

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [dashboard_3.x/605](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.x/605/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.x/605/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.x/605/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.x/605/git)

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [sync-to-downstream_3.x/8328](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8328/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8328/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8328/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8328/git)

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [get-sources-rhpkg-container-build_3.x/8423](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8423/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8423/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8423/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8423/git)

**Pull request merged**
