### PR TITLE
Improve the gitconfig page

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

This PR improves the Gitcofig page to make it possible to update the user name and user email at the same time.

<details>
<summary>Screencast</summary>

https://github.com/eclipse-che/che-dashboard/assets/16220722/c0953e52-b280-4c60-b41e-3b227f624d38

</details>

### What issues does this PR fix or reference?

resolves https://github.com/eclipse/che/issues/22718

### CODE REVIEW

**Comment by artaleks9** [comment]
Verified on Eclipse Che with `quay.io/eclipse/che-dashboard:pr-1031` - the functionality works as expected.

**Review by artaleks9 — APPROVED** [review]

**Review by olexii4 — APPROVED** [review]
LGTM

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
