### PR TITLE
Fix deleting workspace flow

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
This PR fixed several bugs some improvement:
- Fix the create state helper function. Add a test.
- Fix handing 'enter' button when using invalid URL.
- Added handling 'enter' button for 'Load Devfile' on 'Custom Workspace' page.

### What issues does this PR fix or reference?
fixes https://github.com/eclipse/che/issues/19833

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]
I can't say anything about changes but I tested it and it works just fine.

**Comment by sleshchenko** [comment]
@olexii4 please rewrite commit messages to satisfy Semantic Pull Request check

**Comment by olexii4** [comment]
[dashboard-ci-test]

**Review by akurinnoy — APPROVED** [review]

**Comment by sleshchenko** [comment]
it should be cherry-picked to 7.31.x to faster deliver fix to users (like Che Dev Cluster)

**Pull request merged**
