### PR TITLE
chore: cherry-pick #625 to 7.52.x

### PR DESCRIPTION
**Pull request by AObuchow**
### What does this PR do?
Add changes from #625 into the 7.52.x branch.

This back port led to some conflicts, so hopefully I resolved them properly. If not, feel free to either modify this PR or discard it and redo it yourself. 

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/21405

### Is it tested? How?
I ran the automated tests with `npm run test`

### CODE REVIEW

**Review by nickboldt — CHANGES_REQUESTED** [review]
So that the commit log is more clear about blockers fixed for the product, can you update your commit message so it refers to the original commit message? `Add external attributes to workspaces` is much more descriptive than `cherrypick #625`, and will make it immediately obvious when checking the commit log that a fix was ported (and especially WHY).

**Comment by AObuchow** [comment]
> So that the commit log is more clear about blockers fixed for the product, can you update your commit message so it refers to the original commit message? `Add external attributes to workspaces` is much more descriptive than `cherrypick #625`, and will make it immediately obvious when checking the commit log that a fix was ported (and especially WHY).

Sounds good to me - will update it shortly :)

**Review by nickboldt — APPROVED** [review]
LGTM (in terms of commit message metadata) but not an SME so don't trust me here... especially with the comment above about that this cherrypick broke stuff and wasn't completely straightforward.

**Comment by nickboldt** [comment]
dumb question.... do we need to run tests with node 14? it's EOL soon and 16 is the LTS version 

https://endoflife.date/nodejs

**Review by olexii4 — APPROVED** [review]

**Comment by nickboldt** [comment]
the PR checks will never pass because they require docker login to quay.io, which uses secrets that will never be accessible to @AObuchow 's fork, only this repo.

**Comment by nickboldt** [comment]
Closing in favour of #635

**Pull request closed without merging**
