### PR TITLE
Put plugins into devWorkspace.spec.contributions

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
This PR implemented a new rule for putting plugins into DevWorkspace ```.spec.contributions```.

### What issues does this PR fix or reference?
fixes https://github.com/eclipse/che/issues/21737

Знімок екрана 2022-11-21 о 16 57 41

You can test it with [https://eclipse-che.apps.cluster-z2zcs.z2zcs.sandbox1571.opentlc.com](https://eclipse-che.apps.cluster-zxs5p.zxs5p.sandbox2586.opentlc.com/dashboard/)

### CODE REVIEW

**Review by akurinnoy — APPROVED** [review]

**Review by svor — APPROVED** [review]

**Review by l0rd — APPROVED** [review]
I am not sure if we need the `updateDevWorkspacePlugins` (why not just waiting for the update on the devfile registry side?). Apart from the PR looks good. I have tested it and it works. 👍

**Review by ibuziuk — CHANGES_REQUESTED** [review]
tested the PR against dogfooding and for me, neither Intelij nor PyCharm are working. Basically, DW is started but looks like the editor is not processed correctly 

image

theia and vscode seem to work correctly though. @l0rd how important are the Intelij and Pycharm in the context of the contributions epic? I think that our plan is that all editors should continue working after the change

**Comment by l0rd** [comment]
Yes, all editors should continue working.

**Review by ibuziuk — APPROVED** [review]
@olexii4 verified after rebase and all works like a cham \o/ tested with 4 editors

**Pull request merged**
