### PR TITLE
Prevent overwriting the DevWorkspace Operator Config by the Dashboard

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

This PR fixes the workspace startup process to prevent the Dashboard from overwriting the DevWorkspace Operator Config attribute every time the workspace starts.

### What issues does this PR fix or reference?

fixes https://github.com/eclipse/che/issues/22573

### Is it tested? How?

1. Create a DWOC object in your workspaces namespace:
	```yaml
	apiVersion: controller.devfile.io/v1alpha1
	kind: DevWorkspaceOperatorConfig
	metadata:
	  name: custom-dwoc
	  namespace: <your-namespace>
	config:
	  workspace:
	    persistUserHome:
	      enabled: true
	```
2. Reference the DWOC from a devfile:
	```diff
	schemaVersion: 2.2.0
	metadata:
	  name: my-app
	+ attributes:
	+   controller.devfile.io/devworkspace-config:
	+     name: custom-dwoc
	+     namespace: <your-namespace>
	components:
	```
3. Create the workspace and verify it has a correct reference to the DWOC specified:
	```sh
	$ kubectl get dw -o json | jq '.items[0].spec.template.attributes."controller.devfile.io/devworkspace-config"'
	{
	  "name": "custom-dwoc",
	  "namespace": "<your-namespace>"
	}
	```

### CODE REVIEW

**Review by ibuziuk — COMMENTED** [review]
@akurinnoy looks good, but can we possibly add some tests for this functionality?

**Comment by akurinnoy** [comment]
@ibuziuk good point!

**Comment by akurinnoy** [comment]
@ibuziuk tests have been added.

**Review by olexii4 — APPROVED** [review]
LGTM

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
