### PR TITLE
Convert devfile v2 to devfile v1

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

This is cherry-picked https://github.com/eclipse-che/che-dashboard/pull/387

### What issues does this PR fix or reference?

https://issues.redhat.com/browse/CRW-2411

### CODE REVIEW

**Comment by akurinnoy** [comment]
@l0rd I wanted to test the devfiles on minikube locally but factory loading failed with the following message: `Failed to pull image "buildguidanceimage-placeholder"`. My question is how do I get or build that image? or should it be replaced with something else (as `-placeholder` part suggests)?

<details>
<summary>Logs</summary>

```sh
Pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0"

Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0" in 1.800767763s

Created container che-plugin-metadata-broker-v3-4-0

Started container che-plugin-metadata-broker-v3-4-0

Starting plugin metadata broker

All plugin metadata has been successfully processed

List of plugins and editors to install

- eclipse/che-theia/next - Eclipse Theia, get the latest release each day.

Pulling image "quay.io/eclipse/che-theia-endpoint-runtime-binary:next"

Successfully pulled image "quay.io/eclipse/che-theia-endpoint-runtime-binary:next" in 8.740670048s

Created container remote-runtime-injector8my

Started container remote-runtime-injector8my

Pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0"

Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0" in 1.865175913s

Created container che-plugin-artifacts-broker-v3-4-0

Started container che-plugin-artifacts-broker-v3-4-0

Starting plugin artifacts broker

Cleaning /plugins dir

Saving log of installed plugins

All plugin artifacts have been successfully downloaded

Pulling image "quay.io/eclipse/che-jwtproxy:0.10.0"

Successfully pulled image "quay.io/eclipse/che-jwtproxy:0.10.0" in 1.856006786s

Created container che-jwtproxy8cjzyyu9

Started container che-jwtproxy8cjzyyu9

Pulling image "registry.access.redhat.com/ubi8/nodejs-12:1-45"

Successfully pulled image "registry.access.redhat.com/ubi8/nodejs-12:1-45" in 2.640369333s

Created container runtime

Started container runtime

Pulling image "buildguidanceimage-placeholder"

Failed to pull image "buildguidanceimage-placeholder": rpc error: code = Unknown desc = Error response from daemon: pull access denied for buildguidanceimage-placeholder, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

ErrImagePull

Pulling image "quay.io/eclipse/che-theia:next"

Failed to run the workspace: "Unrecoverable event occurred: 'Failed', 'Failed to pull image "buildguidanceimage-placeholder": rpc error: code = Unknown desc = Error response from daemon: pull access denied for buildguidanceimage-placeholder, repository does not exist or may require 'docker login': denied: requested access to the resource is denied', 'workspacepk03jvsm2glwyzf3.workspace-7b6fc66bd9-6v6p5'"
```

</details>

**Comment by l0rd** [comment]
@akurinnoy thanks for testing. This is bad news because that means that the original issue won't be solved by this PR. I have no idea why there is a placeholder and how that can ever work. What about other samples?

**Comment by l0rd** [comment]
> @akurinnoy thanks for testing. This is bad news because that means that the original issue won't be solved by this PR. I have no idea why there is a placeholder and how that can ever work. What about other samples?

I just looked at other samples and they all have the same problem.

**Comment by l0rd** [comment]
Let's merge that as it is. But we cannot close https://issues.redhat.com/browse/CRW-2411 yet. I have added a comment to that issue. Basically we will need to verify with a 2.2 devfile sample.

**Comment by akurinnoy** [comment]
@l0rd 

> I have no idea why there is a placeholder and how that can ever work.

I asked @JPinkney about it and he pointed me to this issue https://github.com/openshift/console/issues/8729.

**Pull request merged**
