### PR TITLE
feat: Make che-dashboard installable to support ctrl-w etc

### PR DESCRIPTION
**Pull request by mtsmfm**
### What does this PR do?

This PR makes che-dashboard PWA and installable to support shortcuts which can't be overridden e.g. ctrl-w

### What issues does this PR fix or reference?

Related to https://github.com/eclipse/che/issues/17844

#### Docs PR

----

You can try this change with ghcr.io/mtsmfm/che-dashboard:pr-5

### CODE REVIEW

**Comment by mtsmfm** [comment]
Rebased. I hope someone review review this PR.

**Comment by sleshchenko** [comment]
@mtsmfm Sorry for such a long delay! We'll review it soon

**Review by sleshchenko — COMMENTED** [review]
Anyway, this PR seems to bring a lot of dependencies, please run [yarn license:generate](https://github.com/eclipse-che/che-dashboard/blob/main/package.json#L17) to check which ones need CQs be created.

**Review by sleshchenko — COMMENTED** [review]
Could you elaborate on

> installable to support shortcuts which can't be overridden e.g. ctrl-w

Who and when will install that shortcuts?

**Comment by mtsmfm** [comment]
> Who and when will install that shortcuts?

che users who want to use shortcuts on terminal area or editor area. 
Currently, ctrl-w always close browser's tab, not editor's tab even if users customize their keyboard shortcut.
They can't be overridden because of browser's restriction.
https://bugs.chromium.org/p/chromium/issues/detail?id=84332

before:

ctrl-w-before

after:

ctrl-w

**Comment by mtsmfm** [comment]
I've noticed in some cases workbox caches too much.
I'll avoid using workbox and make this patch more simply to just make che-dashboard PWA.

**Comment by mtsmfm** [comment]
@sleshchenko I fixed my patch to avoid using workbox for now since cache stuff is not the goal of this PR.
Can you review again?

**Comment by akurinnoy** [comment]
@mtsmfm after the fix I'm not able to install Dashboard, can you check it?

**Comment by mtsmfm** [comment]
@akurinnoy Can you give me a docker image you tried and log?

**Comment by mtsmfm** [comment]
@akurinnoy I've found the cause and force pushed. Can you check again?

**Comment by akurinnoy** [comment]
@mtsmfm sorry for the late response, I somehow missed the notification. 

I resolved conflicts and tested your PR. It works flawlessly! 
Thanks!

**Review by akurinnoy — COMMENTED** [review]
Approved!

**Comment by mtsmfm** [comment]
Thanks!!!

**Pull request merged**
