### PR TITLE
Fix dropdown editor group styles

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Fix dropdown editor group styles.

### What issues does this PR fix or reference?
fixes https://issues.redhat.com/browse/CRW-3448

Знімок екрана 2022-10-19 о 14 27 17
Знімок екрана 2022-10-19 о 14 51 15

### CODE REVIEW

**Review by dmytro-ndp — APPROVED** [review]
LGTM

**Review by akurinnoy — APPROVED** [review]

**Comment by nickboldt** [comment]
hey, while your're fixing styles can you also fix the names of the products referenced? 

See https://issues.redhat.com/browse/CRW-3098 and https://github.com/eclipse/che/issues/21704

**Comment by ibuziuk** [comment]
@nickboldt this is a separate issue, so let's not mixed it up
https://github.com/eclipse/che/issues/21704 is planned for the next sprint

**Review by ibuziuk — APPROVED** [review]
@olexii4 please, backport in 7.54.x

**Comment by nickboldt** [comment]
> @nickboldt this is a separate issue, so let's not mixed it up [eclipse/che#21704](https://github.com/eclipse/che/issues/21704) is planned for the next sprint

Well, main=7.56 is the current sprint and basis for 3.3 so getting it done in the current sprint would be better than waiting until after code freeze to backport it to 7.56.x. I've been asking for that for >4 weeks already :(

**Comment by ibuziuk** [comment]
@nickboldt it should have been raised during the planning in this case. At this point, it is not clear how is it expected to be fixed. 
The dashboard is not going to patch any attributes coming from the plugin registry, so if anything needs to be fixed it should be done on the plugin-registry end. In any case, it is not related to this PR, so please continue the discussion on https://github.com/eclipse/che/issues/21704

**Pull request merged**
