### PR TITLE
fix: Do not set 'ephemeral' storage for the 'Safe' mode

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Do not set 'ephemeral' storage for the 'Safe' mode 

### What issues does this PR fix or reference?

- https://github.com/eclipse/che/issues/22638
- https://issues.redhat.com/browse/CRW-4969 

### Is it tested? How?

- install Eclipse Che and patch the dashboard image 

```
spec:
  components:
    dashboard:
      deployment:
        containers:
          - image: quay.io/eclipse/che-dashboard:pr-967
 ```

- Start an empty workspace
- Add a few files to the workspace and then add a devfile with an image that doesn't exist e.g.

```yaml
schemaVersion: 2.2.0
metadata:
  name: devfile-with-typo
components:
  - name: tools
    container:
      image: quay.io/does/not/exist
```

- Select restart from local Devfile
- Wait for an error message
- Click the "Restart with default devfile" button.
- Wait for the target workspace to restart and open IDE
- See that the devfile exist and the changes are not lost

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Review by akurinnoy — APPROVED** [review]

**Comment by ibuziuk** [comment]
@olexii4 @akurinnoy it looks like smth. is still wrong - after doing the workspace restart based on the local devfile changes disappear from the workspace? am I missing smth. or this PR is not enough to fix the issue

**Comment by dmytro-ndp** [comment]
I can confirm that workspace is still restarting with default devfile using ephemeral Storage Type: https://youtu.be/mFvwfgelhs8?si=43ZyfQOpn_JXtrlA

**Comment by olexii4** [comment]
> https://youtu.be/mFvwfgelhs8?si=43ZyfQOpn_JXtrlA

@ibuziuk We still have an old issue: [Restart based on the local Devfile doesn`t work properly](https://github.com/eclipse/che/issues/22453)

**Comment by akurinnoy** [comment]
@ibuziuk @dmytro-ndp please test the PR.

**Review by dmytro-ndp — APPROVED** [review]
Looks good to merge. Well done!
Verification screencast: https://youtu.be/XrIgFNEz0qY

**Comment by ibuziuk** [comment]
> @ibuziuk We still have an old issue: https://github.com/eclipse/che/issues/22453

yeah, but this is unrelated to the ephemeral mode I believe. @olexii4 Could you please review & approve if all is good with this PR in regard to https://github.com/eclipse/che/issues/22638 ?

**Review by olexii4 — APPROVED** [review]

**Pull request merged**
