### PR TITLE
Align the git services skip-oauth flag with oauth-1 providers

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Use includes filter to handle the bitbucket-server oauth 2 provider. The bitbucket server oauth2 provider name is 'bitbucket', but the corresponding 'skip oauth' item is 'bitbucket-server'.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/22723

### Is it tested? How?

1. Deploy che from the che-server PR image: `quay.io/eclipse/che-server:pr-624`
2. Register Bitbucket Server oauth2 provider.
3. Start a workspace from the Bitbucket-Server repo
4. Reject the Bitbucket-Server authorisation page.
5. Go to `User Preferences` -> `Git Services` tab, see: the authorisation flag is set to `skip authorisation` warning.
6. Click the `three dot` icon of the Bitbucket item and clear the `skip authorisation` flag.
7. Delete the workspace and start the workspace from the Bitbucket-Server again, accept the authorisation page, see: the `skip authorisation` flag is set to `authorised` icon.

### CODE REVIEW

**Comment by olexii4** [comment]
@vinokurig Could you update snapshots?
```yarn --cwd  packages/dashboard-frontend test -u```

**Review by olexii4 — APPROVED** [review]

**Review by akurinnoy — APPROVED** [review]
LGTM

**Comment by artaleks9** [comment]
Verified on Eclipse Che with `quay.io/eclipse/che-server:pr-624` and `quay.io/eclipse/che-dashboard:pr-1020`  - works as expected.

**Review by artaleks9 — APPROVED** [review]

**Comment by vinokurig** [comment]
screenshot-eclipse-che apps rosa sqcr5-629wf-29x 6jy4 p3 openshiftapps com-2024 01 11-14_28_14
screenshot-eclipse-che apps rosa sqcr5-629wf-29x 6jy4 p3 openshiftapps com-2024 01 11-14_20_10

**Pull request merged**
