### PR TITLE
chore: bump dependencies

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

Bump `postcss` package.

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [dashboard_3.x/599](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/dashboard_3.x/599/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/dashboard_3.x/599/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/dashboard_3.x/599/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/dashboard_3.x/599/git)

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [sync-to-downstream_3.x/8228](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8228/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8228/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8228/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8228/git)

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [get-sources-rhpkg-container-build_3.x/8305](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8305/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8305/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8305/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8305/git)

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [get-sources-rhpkg-container-build_3.x/8305](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8305/): [FAILURE](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8305/)<br /><blockquote>dashboard : 3.x :: <a href='https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=66114888'> Failed in  66114888</a> : BREW:BUILD/STATUS:UNKNOWN <br /> FAILURE:; copied to quay</blockquote>

**Pull request merged**
