### PR TITLE
feat: fix for copy paste  issue in chromium environment

### PR DESCRIPTION
**Pull request by Panneerselvam-D**
### What does this PR do?
added acces for clipboard in iframe

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/17475

### CODE REVIEW

**Review by akurinnoy — APPROVED** [review]
@Panneerselvam-D Thank you for the contribution!

**Review by olexii4 — APPROVED** [review]

**Comment by akurinnoy** [comment]
@Panneerselvam-D one more thing you need to do before we can merge your PR it's signing the Eclipse Contributor Agreement https://www.eclipse.org/legal/ECA.php

**Comment by Panneerselvam-D** [comment]
> @Panneerselvam-D one more thing you need to do before we can merge your PR it's signing the Eclipse Contributor Agreement https://www.eclipse.org/legal/ECA.php

ECA updated

**Comment by sleshchenko** [comment]
@Panneerselvam-D please squash your commits and use --sign-off option while committing.

**Pull request merged**
