### PR TITLE
Improvement for the workspace startup failure screen

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

This PR updates:

- failed workspace status indicator and status label;
- workspace startup failure screen
    - to use warning icons and colors (if there are few options)
    - to add a link to edit the workspace object (in OpenShift console)

<details>
<summary>Workspace startup page</summary>

Screenshot 2023-11-23 at 17 03 10

</details>

<details>
<summary>Workspaces list page</summary>

Screenshot 2023-11-23 at 17 03 23

</details>

<details>
<summary>Workspace details page</summary>

Screenshot 2023-11-23 at 17 03 29

</details>

### What issues does this PR fix or reference?

resolves https://github.com/eclipse/che/issues/22640
fixes https://github.com/eclipse/che/issues/22694

### Is it tested? How?

1. Deploy Eclipse Che and use the dashboard image from this PR: **quay.io/eclipse/che-dashboard:pr-1002**
  
	```bash
	kubectl patch -n eclipse-che checluster/eclipse-che --type=json -p="[{\"op\": \"replace\", \"path\": \"/spec/components/dashboard\", \"value\": {deployment: {containers: [{image: \"quay.io/eclipse/che-dashboard:pr-1002\", name: che-dashboard}]}}}]"
	```
	
2. Run a workspace that fails on startup, or create one using this devfile:
	```yaml
	schemaVersion: 2.1.0
	metadata:
	  name: wksp
	  generateName: wksp-
	components:
	  - name: should-fail
	    container:
	      image: non-existing-image-name
	```

3. Wait until workspace fails.

### CODE REVIEW

**Review by olexii4 — APPROVED** [review]
Everything works as expected. 
Знімок екрана 2023-11-27 о 15 50 30
Знімок екрана 2023-11-27 о 16 24 26

**Review by ibuziuk — APPROVED** [review]

**Comment by artaleks9** [comment]
@akurinnoy 
Artifacts of Openshift-CI showed, the `dashboard-happy-path` test is failed due two reasons: 
1) it seems, the infrastructure problem, when the test workspace couldn't run, see the scrrenshot

screenshot-Wait_workspace_readiness


2) all test-steps are done, excluding the last one - stop and delete the test woekspace with the error:
```
Stop the workspace by UI:
     TimeoutError: Waiting for element to be located By(xpath, //tr[td//a[text()='quarkus-api-example-mg59']]//span[@data-testid='workspace-status-indicator']//*[local-name()='svg' and @fill='green'])
```
See screenshot:

screenshot-Stop_the_workspace_by_UI

----

My guess, the locator was changed, and need to fix up:
https://github.com/eclipse/che/blob/main/tests/e2e/pageobjects/dashboard/Workspaces.ts#L72 -->
https://github.com/eclipse/che/blob/main/tests/e2e/pageobjects/dashboard/Workspaces.ts#L220

**Pull request merged**
