### PR TITLE
Cherry-pick changes for #471 to 7.44.x branch

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/471 to the 7.44.x branch

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/21134 in 7.44.x

### Is it tested? How?
See process in original PR

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]
@amisevsk not sure if we really need to cherry-pick though
my understanding is that 2.16 might not be built on top of 7.44.x but on the later version

**Review by benoitf — APPROVED** [review]

**Comment by amisevsk** [comment]
> not sure if we really need to cherry-pick though
> my understanding is that 2.16 might not be built on top of 7.44.x but on the later version

I opened this PR because of https://github.com/eclipse-che/che-dashboard/pull/471#issuecomment-1064044467, but if it's not needed / wanted that's fine too :D

**Comment by ibuziuk** [comment]
looks like it is needed - the next version of the project is going to be based on 7.44.x

**Comment by nickboldt** [comment]
merged, for inclusion in 7.44 ==> Dev Spaces 3.0

**Pull request merged**
