### PR TITLE
Run linters and formatter on pre-commit hook

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

Used `husky` to create a pre-commit hook to run linters and formatter.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20379

### Is it tested? How?

1. Apart from other changes, change some to TS files, so that changes should be against eslint and tsfmt rules, e.g
    - replace single-quotes (`'`) with double-quotes (`"`)
    - leave several empty lines in the row.

2. Stage changes and then commit them.
3. Inspect the commit.

### CODE REVIEW

**Review by sleshchenko — COMMENTED** [review]
As far as I understand it requires node, yarn and all dependencies being installed before commit.
I assume it breaks release
https://github.com/eclipse-che/che-dashboard/blob/main/.github/workflows/release.yml#L139

Maybe it makes sense to add pre-commit into gitignore, and provide developers command into package.json is they want to initialize it?

**Comment by dmytro-ndp** [comment]
[dashboard-ci-test]

**Comment by dmytro-ndp** [comment]
[dashboard-ci-test]

**Comment by akurinnoy** [comment]
Closing in favor of https://github.com/eclipse-che/che-dashboard/pull/370

**Pull request closed without merging**
