### PR TITLE
Update Yarn 1 lockfile for downstream build

### PR DESCRIPTION
**Pull request by SDawley**
### What does this PR do?
Updates the lockfile used in the downstream DevSpaces builds.

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-7638

### CODE REVIEW

**Review by akurinnoy — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]

**Review by olexii4 — APPROVED** [review]

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [dashboard_3.18/3](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.18/3/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.18/3/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.18/3/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.18/3/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [sync-to-downstream_3.18/134](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.18/134/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.18/134/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.18/134/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.18/134/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [push-latest-container-to-quay_3.18/14](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.18/14/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.18/14/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.18/14/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.18/14/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [get-sources-rhpkg-container-build_3.18/105](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/105/): [SUCCESS](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/105/)<br /><blockquote>dashboard : 3.18 :: <a href='https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=66200959'> Build  66200959</a> : <a href=https://quay.io/devspaces/dashboard-rhel9:3.18-1>quay.io/devspaces/dashboard-rhel9:3.18-1</a> <br /> SUCCESS; copied to quay; <a href=https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.18/14/>/DS_CI/push-latest-container-to-quay_3.18/14</a> triggered</blockquote>

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [update-digests_3.18/106](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/update-digests_3.18/106/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/update-digests_3.18/106/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/update-digests_3.18/106/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/update-digests_3.18/106/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [dashboard_3.18/3](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.18/3/): [SUCCESS](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/dashboard_3.18/3/)<br /><blockquote>Upstream sync done; <a href=https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.18/134/>/DS_CI/sync-to-downstream_3.18/134</a> triggered</blockquote>

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [operator-bundle_3.18/106](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/operator-bundle_3.18/106/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/operator-bundle_3.18/106/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/operator-bundle_3.18/106/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/operator-bundle_3.18/106/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [get-sources-rhpkg-container-build_3.18/106](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/106/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/106/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/106/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/106/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [get-sources-rhpkg-container-build_3.18/106](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/106/): [FAILURE](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/106/)<br /><blockquote>devspaces-operator-bundle : 3.18 :: <a href='https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=66201178'> Failed in  66201178</a> : BREW:BUILD/STATUS:UNKNOWN <br /> FAILURE:; copied to quay</blockquote>

**Pull request merged**
