### PR TITLE
Remove Devfile V1 support

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

This PR drops the Devfile V1 support and removes the `devfile-converter` package.

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]

**Comment by olexii4** [comment]
I have tested these changes:

1. Creating a new workspace from the repo without any devfiles:

```{CHE-server}#https://github.com/olexii4/wildfly-devfile-examples```

Знімок екрана 2024-04-08 о 16 54 04

2. Creating a new workspace from the nonexisting repo:
```
{CHE-server}#https://github.com/eclipse-che/che-dashboard88888888888
```

Знімок екрана 2024-04-08 о 17 18 22

@akurinnoy Previously it created a new workspace from the repo without any devfiles without any interruption. Is it expecting behavior?

**Comment by akurinnoy** [comment]
@olexii4 thanks for testing this PR, I'll workaround this on the dashboard side

**Review by olexii4 — APPROVED** [review]
LGTM

**Pull request merged**
