### PR TITLE
Apply DevWorkspace resources

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

This PR fixes the bug that prevents applying pre-built resources from the devfile registry pod.

It is related to https://issues.redhat.com/browse/CRW-6228

### CODE REVIEW

**Review by svor — APPROVED** [review]
lgtm

**Review by svor — APPROVED** [review]
Tested with DS 3.13 and dashboard image quay.io/eclipse/che-dashboard:pr-1091
works as expected:
screenshot-devspaces apps ci-ln-lg955pb-76ef8 aws-2 ci openshift org-2024 04 09-17_03_24

**Review by olexii4 — APPROVED** [review]
LGTM

**Review by dmytro-ndp — APPROVED** [review]
PR looks good to merge.

Tested on **DS 3.13.0.RC-devspaces-operator-bundle:3.13-99** by creating workspace using from user dashboard deployed using container image quay.io/eclipse/che-dashboard:pr-1091 :
- from Java Lombok sample in Dashboard
- Empty workspace sample in Dashboard
- from factory URL https://raw.githubusercontent.com/dmytro-ndp/registry/main/stacks/python/2.1.0/devfile.yaml

Tested on **Eclipse Che Next** by creating workspace using from user dashboard deployed using container image quay.io/eclipse/che-dashboard:pr-1091:
- from Python sample in Dashboard
- Empty workspace sample in Dashboard
- from Factory URL https://raw.githubusercontent.com/dmytro-ndp/registry/54b174151d16898ae07a380ef774ad46b5ad7196/stacks/python/2.1.0/devfile.yaml

**Pull request merged**
