### PR TITLE
chore: refresh access token when workspace is starting

### PR DESCRIPTION
**Pull request by svor**
### What does this PR do?
Refreshes OAuth access token when the devWorkspace is starting/restarting.
It does in a few steps:
- sends a request to che-server to check the OAuth token
- if che-server returns an error, open an authentication page to authenticate

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-3928

### Is it tested? How?

1. Update CheCluster CR with `vsvydenko/che-dashboard:7` dashboard image.
2. Configure GitLab Oauth as per the documentation https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-gitlab/
3. Use factory to start a workspace with private project
4. Wait 2 hours when the access token is expired 
5. Try to restart the workspace and execute `git pull` in the workspace

https://user-images.githubusercontent.com/1271546/221356558-5e2e87ec-e665-4293-b4e3-72f357d80826.mp4

### CODE REVIEW

**Review by olexii4 — COMMENTED** [review]
I can see some problems with refreshing the token:
```
Status Code: 500 Internal Server Error
...
Referrer Policy: strict-origin-when-cross-origin
```

Знімок екрана 2023-03-01 о 14 19 02

@akurinnoy  WDYT?

**Comment by akurinnoy** [comment]
@olexii4 I also can reproduce this issue when starting workspaces with a public repo. However, this should not block this PR because the problem seems to be on the che-server side.

**Comment by svor** [comment]
@olexii4 @akurinnoy thanks for reviewing 

>I can see some problems with refreshing the token:
>Status Code: 500 Internal Server Error
>...
>Referrer Policy: strict-origin-when-cross-origin

As far as I understand it's an expected behavior, we see this error because GitHub OAuth is not configured on the cluster.
This error should be caught on the dashboard side: https://github.com/eclipse-che/che-dashboard/pull/738/files#diff-c1a26f895b5713758275335441c556fffd0d06379684f741dfef6456a2866104R45-R64

@vinokurig may correct me if I'm wrong

**Comment by vinokurig** [comment]
> As far as I understand it's an expected behavior, we see this error because GitHub OAuth is not configured on the cluster.
This error should be caught on the dashboard side: https://github.com/eclipse-che/che-dashboard/pull/738/files#diff-c1a26f895b5713758275335441c556fffd0d06379684f741dfef6456a2866104R45-R64
>
@vinokurig may correct me if I'm wrong

I am not sure about this error, I don't think that `che-server` can pass to dashboard errors other then `Unauthorised`.

**Comment by svor** [comment]
Currently we see **Status Code: 500 Internal Server Error** when trying to restart the project without OAuth configuration:
And the exception's message is `{"message":"Unsupported OAuth provider github"}` 
Screenshot from 2023-03-06 15-05-40

With these changes a git access token is going to be refreshed each time when the workspace is starting, even if it is the first time when the workspace is starting(workspace creation) . That's why we see the exception during the workspace creation, because GitHub OAuth is not configured on the fresh OS cluster.

**Comment by svor** [comment]
@akurinnoy @olexii4 @vinokurig could you please take a look

**Review by akurinnoy — APPROVED** [review]

**Pull request merged**
